sudo: false
language: python
cache: pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.8"
  - "pypy2"
  - "pypy2.7"
  - "pypy3"
  - "pypy3.5"

install: pip install coverage tox-travis tox tox-pip-extensions
script: tox

after_success: bash <(curl -s https://codecov.io/bash)
